# Generated by Django 5.2.3 on 2025-06-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='external_id',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_email',
            field=models.EmailField(default='unknown', max_length=255),
        ),
    ]
